/**
 * Mealapp api descriptor
 * This is a meal app android client.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: palko9711@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';


export interface CategoryList { 
    categories?: Array<Category>;
}
