/**
 * Mealapp api descriptor
 * This is a meal app android client.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: palko9711@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { CategoryList } from '../model/categoryList';
import { CategoryListFilter } from '../model/categoryListFilter';
import { MealList } from '../model/mealList';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { Observable } from 'rxjs';


@Injectable()
export class FoodService {

    protected basePath = 'http://themealdb.com/api/json/v1/1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * List all meal categories
     * Returns a list of meal categories.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCategories(observe?: 'body', reportProgress?: boolean): Observable<CategoryList>;
    public getCategories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CategoryList>>;
    public getCategories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CategoryList>>;
    public getCategories(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CategoryList>(`${this.basePath}/categories.php`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get meal details by id
     *
     * @param i The meal that needs to be fetched. Use 52772 for testing.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMealById(i: string, observe?: 'body', reportProgress?: boolean): Observable<MealList>;
    public getMealById(i: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MealList>>;
    public getMealById(i: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MealList>>;
    public getMealById(i: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (i === null || i === undefined) {
            throw new Error('Required parameter i was null or undefined when calling getMealById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (i !== undefined && i !== null) {
            queryParameters = queryParameters.set('i', <any>i);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MealList>(`${this.basePath}/lookup.php`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get meals by category
     *
     * @param c The category that needs to be fetched. Use Seafood for testing.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMealsByCategory(c: string, observe?: 'body', reportProgress?: boolean): Observable<CategoryListFilter>;
    public getMealsByCategory(c: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CategoryListFilter>>;
    public getMealsByCategory(c: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CategoryListFilter>>;
    public getMealsByCategory(c: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (c === null || c === undefined) {
            throw new Error('Required parameter c was null or undefined when calling getMealsByCategory.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (c !== undefined && c !== null) {
            queryParameters = queryParameters.set('c', <any>c);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<CategoryListFilter>(`${this.basePath}/filter.php`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get random meal
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRandomMeal(observe?: 'body', reportProgress?: boolean): Observable<MealList>;
    public getRandomMeal(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MealList>>;
    public getRandomMeal(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MealList>>;
    public getRandomMeal(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MealList>(`${this.basePath}/random.php`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search meals by name
     *
     * @param s The meal that needs to be fetched. Use arr for testing.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchMealByName(s: string, observe?: 'body', reportProgress?: boolean): Observable<MealList>;
    public searchMealByName(s: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MealList>>;
    public searchMealByName(s: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MealList>>;
    public searchMealByName(s: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (s === null || s === undefined) {
            throw new Error('Required parameter s was null or undefined when calling searchMealByName.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (s !== undefined && s !== null) {
            queryParameters = queryParameters.set('s', <any>s);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MealList>(`${this.basePath}/search.php`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
